### ISSUE TITLE
Transformer's performance deteriorates after MRT

### ISSUE THREAD

**Issue by yongchanghao** [Jiaqiang-Ruan/MinimumRiskTraining#1]
I fine-tuned a transformer model measured about 44 BLEU by MRT with hyper-parameters left as default. After several epochs, the BLEU score is down to around 24.

Is there any prerequisite operations before MRT?

**Comment by Jiaqiang-Ruan** [comment]
MRT is hard to optimize and is very vulnerable. It happens to me that BLEU suddenly drops dramatically without apparent bug too. Actually I didn't figure out the solution for this. Sorry to reflex on this issue after such a long time.
